### ISSUE TITLE
details about training and evaluate on the ActorsHQ dataset.

### ISSUE THREAD

**Issue by liwenssss** [lizhe00/AnimatableGaussians#48]
Hi, I tried your code on the ActorsHQ dataset (actors1/seq1). I used 46 cameras for training and 1 view for evaluation. My config settings are as follows:

```
train:
  dataset: MvRgbDatasetActorsHQ
  data:
    subject_name: actor01
    data_dir: /nfs/datasets/humanrf-dataset/tmp/actorshq/Actor01/Sequence1/
    frame_range: &id001
    - 48
    - 2177
    - 1
    used_cam_ids: [4, 5, 6, 7, 20, 21, 22, 23, 36, 37, 38, 39, 52, 53, 54, 55, 76, 77, 78, 79, 92, 93, 94, 95, 108, 109, 110, 111, 125, 126, 130, 131, 134, 135, 138, 139, 142, 143, 146, 147, 150, 151, 154, 155, 158, 159]
    load_smpl_pos_map: true

......

test:
  dataset: MvRgbDatasetActorsHQ
  data:
    data_dir: /nfs/datasets/humanrf-dataset/tmp/actorshq/Actor01/Sequence1/
    frame_range: *id001
    subject_name: actor01
  view_setting: camera 
  render_view_idx: 127
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  n_pca: 20
  sigma_pca: 2.0
  prev_ckpt: ./results/actor01/avatar/batch_800000
model:
  with_viewdirs: true
  random_style: false
```
I tested all the 2129 frames under Cam128 (render_view_idx 127) and got the following results:

`
Count: 2129, PSNR: 28.642307322254315, SSIM: 0.922512511663277, LPIPS: 0.08213683989418678
`
The results seem a little lower than those in the paper. Is this normal?
